name: ðŸš€ Automatic Deploy Website to 000WebHost on Push

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "web-deploy"
  web-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: ðŸŽ‰ Start prompt
        run: echo Start automatic deployment
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: ðŸšš Get latest code
        uses: actions/checkout@v3
      
      - name: ðŸ“‚ Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: files.000webhost.com
          username: ${{ secrets.PLATFORM_USERNAME }}
          password: ${{ secrets.PLATFORM_PASSEORD }}
          server-dir: public_html/
          # dangerous-clean-slate: true
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            .htaccess
            .idea/**
            README.md
            LICENSE
            DESIGN/**
            DOCUMENTATION/**
            assets/**
            Database/DatabaseSchema.sql

      - name: ðŸŽ‰ Completion prompt
        run: |
          echo Automatic deployment completed
          echo Please go to Test-Website to check
